/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package nuevoform;

import javax.swing.DefaultListModel;

/**
 *
 * @author Usuario
 */
public class Contactos extends javax.swing.JInternalFrame {
    
    DefaultListModel model = new DefaultListModel();
    String Nonbre = "";
    String Valor = "";
    String Direccion = "";
    String numero = "";
    String Correo = "";
    int lugar = 0;
    private String Nombre;

    /**
     * Creates new form Contactos
     */
    public Contactos() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTxtNombre = new javax.swing.JTextField();
        jTxtDireccion5 = new javax.swing.JTextField();
        jTxtTelefono = new javax.swing.JTextField();
        jTextCorreo = new javax.swing.JTextField();
        Guardar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 0));
        setClosable(true);
        setForeground(new java.awt.Color(102, 204, 0));
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 25, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel2.setText("Direccion:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel3.setText("Telefono:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel4.setText("Correo:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        jTxtNombre.setBackground(new java.awt.Color(153, 255, 204));
        jTxtNombre.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jTxtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(jTxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 221, -1));

        jTxtDireccion5.setBackground(new java.awt.Color(204, 255, 204));
        jTxtDireccion5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtDireccion5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTxtDireccion5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 100, 32));

        jTxtTelefono.setBackground(new java.awt.Color(153, 255, 204));
        jTxtTelefono.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jTxtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtTelefonoActionPerformed(evt);
            }
        });
        getContentPane().add(jTxtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 221, -1));

        jTextCorreo.setBackground(new java.awt.Color(153, 255, 204));
        jTextCorreo.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jTextCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCorreoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 221, -1));

        Guardar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Pictures\\285657_floppy_guardar_save_icon.png")); // NOI18N
        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        getContentPane().add(Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Pictures\\6127253_media_multimedia_player_refresh_repeat_icon.png")); // NOI18N
        jButton2.setText("Actualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Pictures\\6217227_bin_fly_garbage_trash_icon.png")); // NOI18N
        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, -1, -1));

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Pictures\\3688492_exit_export_logout_out_icon.png")); // NOI18N
        jButton4.setText("Salir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 340, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 830, -1));

        jList1.setBackground(new java.awt.Color(255, 255, 204));
        jList1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 490, 280));

        jComboBox1.setBackground(new java.awt.Color(153, 255, 204));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Selecione una opcion", "Pichincha, Quito", "Cuenca", "Guayaquil", "Loja" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, 32));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Pictures\\372903_username_name_full_user_round_icon.png")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 24, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Pictures\\2849828_pointer_map_location_place_multimedia_icon.png")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 92, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Pictures\\9024698_phone_call_light_icon.png")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Pictures\\1181190_email_gmail_google_mail_icon.png")); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jLabel9.setBackground(new java.awt.Color(51, 51, 51));
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("NOMBRE         l    DIRECCIÓN      l      TELEFONO     l  CORREO");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 450, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
model.remove(lugar);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTxtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNombreActionPerformed

    private void jTxtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtTelefonoActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        Nombre = jTxtNombre.getText();
    Valor = jTxtDireccion5.getText();
    numero = jTxtTelefono.getText();
    Correo = jTextCorreo.getText();
    Direccion = (String) jComboBox1.getSelectedItem(); //obtiene la selección del usuario en el JComboBox
    model.addElement(Nombre+" - "+Direccion+" - "+Valor+" - "+numero+" - "+Correo);
    jList1.setModel(model);
       // TODO add your handling code here:
    }//GEN-LAST:event_GuardarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  lugar = jList1.getSelectedIndex();
        Valor = jTxtNombre.getText() + "   " + jTxtDireccion5.getText() + "   " + jTxtTelefono.getText() + "    " + jTextCorreo.getText();
        System.err.println("valor" + Valor + "  " + lugar);
        model.set(lugar, Valor);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCorreoActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
      jComboBox1.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        lugar = jComboBox1.getSelectedIndex();
    }
});
  
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTxtDireccion5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtDireccion5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtDireccion5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Guardar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextCorreo;
    private javax.swing.JTextField jTxtDireccion5;
    private javax.swing.JTextField jTxtNombre;
    private javax.swing.JTextField jTxtTelefono;
    // End of variables declaration//GEN-END:variables
}
